export type metricsType = {
    deltatemp: number,
    winddirection: string,
    wind: number,
    gust: number,
    precipitation: number,
    prevprecipitation: number,
    probabilityCnt: number,
    probabilitySum: number,
    probability: number,
    mintemp: number,
    maxtemp: number,
    minhumi: number,
    maxhumi: number,
    minsoilhumi: number,
    maxsoilhumi: number,
    r2: number,
    r3: number,
    r6: number,
    t3: number,
}